// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class Dog
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Breed { get; set; }

    public int? Age { get; set; }

    public virtual ICollection<RaceDog> RaceDogs { get; set; } = new List<RaceDog>();

    public virtual ICollection<TicketDetail> TicketDetails { get; set; } = new List<TicketDetail>();
}