// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class RaceDog
{
    public int RaceId { get; set; }

    public int DogId { get; set; }

    public int StartPosition { get; set; }

    public decimal Odds { get; set; }

    public bool? IsAvailable { get; set; }

    public bool? IsWinner { get; set; }

    public virtual Dog Dog { get; set; }

    public virtual Race Race { get; set; }
}