// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class Race
{
    public int Id { get; set; }

    public int RaceStatusId { get; set; }

    public DateTime? ScheduledAt { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? FinishedAt { get; set; }

    public virtual ICollection<RaceDog> RaceDogs { get; set; } = new List<RaceDog>();

    public virtual ICollection<TicketDetail> TicketDetails { get; set; } = new List<TicketDetail>();
}