// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class TicketDetail
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public int RaceId { get; set; }

    public int DogId { get; set; }

    public virtual Dog Dog { get; set; }

    public virtual Race Race { get; set; }

    public virtual Ticket Ticket { get; set; }
}