// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class Ticket
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal PotentialWinning { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte StatusId { get; set; }

    public virtual ICollection<TicketDetail> TicketDetails { get; set; } = new List<TicketDetail>();

    public virtual User User { get; set; }
}