// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawRace.DataAccess.Models;

public partial class User
{
    public int Id { get; set; }

    public Guid Guidid { get; set; }

    public string NickName { get; set; }

    public string IpAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}